FROM ruby:<%= ruby_version %>

MAINTAINER Moritz Schepp <moritz.schepp@gmail.com>

VOLUME /opt/kor/shared
VOLUME /etc/ssmtp

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential libxml2-dev libxslt-dev git-core curl libssl-dev && \
    apt-get install -y libmysqlclient-dev imagemagick libav-tools zip libreadline6-dev ssmtp file && \
    apt-get clean && \
    echo 'gem: --no-ri --no-rdoc' >> /etc/gemrc && \
    useradd -m kor

RUN mkdir -p /opt/kor/shared/data
ADD tmp/kor.tar /opt/kor/current

WORKDIR /opt/kor/current

<% if rails_env == 'production' %>
RUN ln -sfn /opt/kor/shared/database.yml /opt/kor/current/config/database.yml && \
    ln -sfn /opt/kor/shared/kor.yml /opt/kor/current/config/kor.yml && \
    ln -sfn /opt/kor/shared/kor.app.yml /opt/kor/current/config/kor.app.yml && \
    ln -sfn /opt/kor/shared/legal.txt /opt/kor/current/config/legal.txt && \
    ln -sfn /opt/kor/shared/contact.txt /opt/kor/current/config/contact.txt && \
    ln -sfn /opt/kor/shared/data /opt/kor/current/data && \
    ln -sfn /opt/kor/shared/log /opt/kor/current/log
<% else %>
RUN mkdir -p /opt/kor/current/data && \
    mkdir -p /opt/kor/current/log && \
    cp /opt/kor/current/config/database.yml.example.ci /opt/kor/current/config/database.yml && \
    touch /opt/kor/current/config/kor.yml && \
    touch /opt/kor/current/config/kor.app.yml && \
    cp /opt/kor/current/config/legal.txt.example /opt/kor/current/config/legal.txt && \
    cp /opt/kor/current/config/legal.txt.example /opt/kor/current/config/contact.txt
<% end %>

<% if rails_env == 'test' %>
ENV RAILS_ENV test
ENV HEADLESS true
<% end %>

<% if rails_env == 'production' %>
ENV RAILS_ENV production
EXPOSE 8000
<% end %>

<% if rails_env == 'test' %>
RUN cd /opt && \
    apt-get install -y zip libgconf-2-4 chromium && \
    wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    ln -sfn /opt/chromedriver /usr/bin/chromedriver && \
    rm chromedriver_linux64.zip
<% end %>

RUN gem update bundler

<% if rails_env == 'test' %>
  RUN bash -c "bundle install --path /opt/kor/bundle --without development production" kor
<% end %>

<% if rails_env == 'production' %>
  RUN bash -c "bundle install --path /opt/kor/bundle --without development test" kor

  ENV RAILS_SERVE_STATIC_FILES true
  RUN bash -c "RAILS_GROUPS=assets bundle exec rake assets:precompile" kor
<% end %>

ADD public/*.css /opt/kor/current/public/
ADD public/*.js /opt/kor/current/public/
ADD public/fonts /opt/kor/current/public/fonts