Feature: Navigation
  Scenario: User Menu
    Given I am logged in as "jdoe"
    Then I should see "Search" within widget "kor-menu"
    And I should see "New entries" within widget "kor-menu"
    And I should see "Clipboard" within widget "kor-menu"
    And I should see "Global collections" within widget "kor-menu"
    And I should see "Personal collections" within widget "kor-menu"
    And I should see "Shared collections" within widget "kor-menu"
    And I should see "Published collections" within widget "kor-menu"
    And I should see link "Edit profile" within widget "kor-header"
    And I should see "Statistics" within widget "kor-menu"
    And I should not see "Administration" within widget "kor-menu"
    And I should not see option "Create entity" within widget "kor-menu"
    And I should not see "Invalid entities" within widget "kor-menu"
    And I should not see "New entities" within widget "kor-menu"
    And I should not see "Admin" within widget "kor-menu"

  Scenario: Admin Menu
    Given I am logged in as "admin"
    Then I should see "Search" within widget "kor-menu"
    And I should see "New entries" within widget "kor-menu"
    And I should see "Clipboard" within widget "kor-menu"
    And I should see "Global collections" within widget "kor-menu"
    And I should see "Personal collections" within widget "kor-menu"
    And I should see "Shared collections" within widget "kor-menu"
    And I should see "Published collections" within widget "kor-menu"
    And I should see link "Edit profile" within widget "kor-header"
    And I should see "Statistics" within widget "kor-menu"
    And I should see option "Create entity" within widget "kor-menu"
    And I should see "Invalid entities" within widget "kor-menu"
    And I should see "New entities" within widget "kor-menu"
    And I should see "Settings" within widget "kor-menu"
    And I should see "Relations" within widget "kor-menu"
    And I should see "Entity types" within widget "kor-menu"
    And I should see "Domains" within widget "kor-menu"
    And I should see "User groups" within widget "kor-menu"
    And I should see "Users" within widget "kor-menu"
    